name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Run test suite

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install itspriddle/gh-shellcheck
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh extension install itspriddle/gh-shellcheck

      - name: Run shellcheck
        run: |
          gh shellcheck
